// This file will be auto-generated by FlutterFire CLI
// Run: flutter pub get
// Then: flutterfire configure
// 
// For now, Firebase will use google-services.json for Android configuration
// If you need iOS/Web support, run the flutterfire configure command
